name: Workflow CI/CD GPI JS

# Control when the action will run

on:
  push: 
     branches: 
        - master
  
  # Allow you to run this workflow manualy from the actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main  
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: dev.gpijalansuci.org
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASS }}
          local-dir: dist/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            public
            src
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: Dev
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: test.gpijalansuci.org 
          username: ${{ secrets.TEST_USER }}
          password: ${{ secrets.TEST_PASS }}
          local-dir: dist/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            public
            src
  Production:
      runs-on: ubuntu-latest
      environment: Production
      needs: Test
      steps: 
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Use Node.js 16
          uses: actions/setup-node@v3
          with:
            node-version: '16'

        - name: 🔨 Build Project
          run: |
            npm install
            npm run build

        - name: Sync files to hosting
          uses: SamKirkland/FTP-Deploy-Action@4.3.2
          with:
            server: gpijalansuci.org
            username: ${{ secrets.PROD_USER }}
            password: ${{ secrets.PROD_PASS }}
            local-dir: dist/
            exclude: |
              **/.git*
              **/.git*/**
              **/node_modules/**
              public
              src
